// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: installation.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const installationCreateNewInstallation = `-- name: InstallationCreateNewInstallation :one
INSERT INTO installation (
        installation_id,
        notification_token,
        locale,
        device_manufacturer,
        device_os,
        device_os_version,
        app_version
    )
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, installation_id, notification_token, locale, timezone_offset_in_minutes, device_manufacturer, device_os, device_os_version, app_version, created_at, updated_at, deleted_at, attach_to, last_attach_to
`

type InstallationCreateNewInstallationParams struct {
	InstallationID     uuid.UUID   `json:"installation_id"`
	NotificationToken  pgtype.Text `json:"notification_token"`
	Locale             string      `json:"locale"`
	DeviceManufacturer string      `json:"device_manufacturer"`
	DeviceOs           string      `json:"device_os"`
	DeviceOsVersion    string      `json:"device_os_version"`
	AppVersion         string      `json:"app_version"`
}

// InstallationCreateNewInstallation
//
//	INSERT INTO installation (
//	        installation_id,
//	        notification_token,
//	        locale,
//	        device_manufacturer,
//	        device_os,
//	        device_os_version,
//	        app_version
//	    )
//	VALUES ($1, $2, $3, $4, $5, $6, $7)
//	RETURNING id, installation_id, notification_token, locale, timezone_offset_in_minutes, device_manufacturer, device_os, device_os_version, app_version, created_at, updated_at, deleted_at, attach_to, last_attach_to
func (q *Queries) InstallationCreateNewInstallation(ctx context.Context, arg InstallationCreateNewInstallationParams) (Installation, error) {
	row := q.db.QueryRow(ctx, installationCreateNewInstallation,
		arg.InstallationID,
		arg.NotificationToken,
		arg.Locale,
		arg.DeviceManufacturer,
		arg.DeviceOs,
		arg.DeviceOsVersion,
		arg.AppVersion,
	)
	var i Installation
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.NotificationToken,
		&i.Locale,
		&i.TimezoneOffsetInMinutes,
		&i.DeviceManufacturer,
		&i.DeviceOs,
		&i.DeviceOsVersion,
		&i.AppVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AttachTo,
		&i.LastAttachTo,
	)
	return i, err
}

const installationGetInstallationUsingUUID = `-- name: InstallationGetInstallationUsingUUID :one
SELECT id, installation_id, notification_token, locale, timezone_offset_in_minutes, device_manufacturer, device_os, device_os_version, app_version, created_at, updated_at, deleted_at, attach_to, last_attach_to
FROM installation
WHERE installation_id = $1
    AND deleted_at IS NULL
LIMIT 1
`

// InstallationGetInstallationUsingUUID
//
//	SELECT id, installation_id, notification_token, locale, timezone_offset_in_minutes, device_manufacturer, device_os, device_os_version, app_version, created_at, updated_at, deleted_at, attach_to, last_attach_to
//	FROM installation
//	WHERE installation_id = $1
//	    AND deleted_at IS NULL
//	LIMIT 1
func (q *Queries) InstallationGetInstallationUsingUUID(ctx context.Context, installationID uuid.UUID) (Installation, error) {
	row := q.db.QueryRow(ctx, installationGetInstallationUsingUUID, installationID)
	var i Installation
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.NotificationToken,
		&i.Locale,
		&i.TimezoneOffsetInMinutes,
		&i.DeviceManufacturer,
		&i.DeviceOs,
		&i.DeviceOsVersion,
		&i.AppVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AttachTo,
		&i.LastAttachTo,
	)
	return i, err
}

const installationGetInstallationUsingUUIdAndWhereAttachTo = `-- name: InstallationGetInstallationUsingUUIdAndWhereAttachTo :one
SELECT id, installation_id, notification_token, locale, timezone_offset_in_minutes, device_manufacturer, device_os, device_os_version, app_version, created_at, updated_at, deleted_at, attach_to, last_attach_to
FROM installation
WHERE installation_id = $1
    AND attach_to = $2
    AND deleted_at IS NULL
LIMIT 1
`

type InstallationGetInstallationUsingUUIdAndWhereAttachToParams struct {
	InstallationID uuid.UUID   `json:"installation_id"`
	AttachTo       pgtype.Int4 `json:"attach_to"`
}

// InstallationGetInstallationUsingUUIdAndWhereAttachTo
//
//	SELECT id, installation_id, notification_token, locale, timezone_offset_in_minutes, device_manufacturer, device_os, device_os_version, app_version, created_at, updated_at, deleted_at, attach_to, last_attach_to
//	FROM installation
//	WHERE installation_id = $1
//	    AND attach_to = $2
//	    AND deleted_at IS NULL
//	LIMIT 1
func (q *Queries) InstallationGetInstallationUsingUUIdAndWhereAttachTo(ctx context.Context, arg InstallationGetInstallationUsingUUIdAndWhereAttachToParams) (Installation, error) {
	row := q.db.QueryRow(ctx, installationGetInstallationUsingUUIdAndWhereAttachTo, arg.InstallationID, arg.AttachTo)
	var i Installation
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.NotificationToken,
		&i.Locale,
		&i.TimezoneOffsetInMinutes,
		&i.DeviceManufacturer,
		&i.DeviceOs,
		&i.DeviceOsVersion,
		&i.AppVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AttachTo,
		&i.LastAttachTo,
	)
	return i, err
}

const installationSoftDeleteInstallation = `-- name: InstallationSoftDeleteInstallation :exec
UPDATE installation
SET deleted_at = NOW()
WHERE id = $1
`

// InstallationSoftDeleteInstallation
//
//	UPDATE installation
//	SET deleted_at = NOW()
//	WHERE id = $1
func (q *Queries) InstallationSoftDeleteInstallation(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, installationSoftDeleteInstallation, id)
	return err
}

const installationUpdateInstallation = `-- name: InstallationUpdateInstallation :exec
UPDATE installation
SET notification_token = $3,
    locale = $4,
    timezone_Offset_in_minutes = $5
WHERE id = $1
    AND installation_id = $2
    AND deleted_at IS NULL
`

type InstallationUpdateInstallationParams struct {
	ID                      int32       `json:"id"`
	InstallationID          uuid.UUID   `json:"installation_id"`
	NotificationToken       pgtype.Text `json:"notification_token"`
	Locale                  string      `json:"locale"`
	TimezoneOffsetInMinutes int32       `json:"timezone_offset_in_minutes"`
}

// InstallationUpdateInstallation
//
//	UPDATE installation
//	SET notification_token = $3,
//	    locale = $4,
//	    timezone_Offset_in_minutes = $5
//	WHERE id = $1
//	    AND installation_id = $2
//	    AND deleted_at IS NULL
func (q *Queries) InstallationUpdateInstallation(ctx context.Context, arg InstallationUpdateInstallationParams) error {
	_, err := q.db.Exec(ctx, installationUpdateInstallation,
		arg.ID,
		arg.InstallationID,
		arg.NotificationToken,
		arg.Locale,
		arg.TimezoneOffsetInMinutes,
	)
	return err
}
