// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: permission_and_role.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const perRollAddPermissionToRole = `-- name: PerRollAddPermissionToRole :exec
INSERT INTO role_permission(role_id, permission_id)
VALUES($1, $2)
`

type PerRollAddPermissionToRoleParams struct {
	RoleID       int32 `json:"role_id"`
	PermissionID int32 `json:"permission_id"`
}

// PerRollAddPermissionToRole
//
//	INSERT INTO role_permission(role_id, permission_id)
//	VALUES($1, $2)
func (q *Queries) PerRollAddPermissionToRole(ctx context.Context, arg PerRollAddPermissionToRoleParams) error {
	_, err := q.db.Exec(ctx, perRollAddPermissionToRole, arg.RoleID, arg.PermissionID)
	return err
}

const perRollCreateNewPermission = `-- name: PerRollCreateNewPermission :one
INSERT INTO permission(name)
VALUES($1)
RETURNING id, name, created_at, updated_at, deleted_at
`

// PerRollCreateNewPermission
//
//	INSERT INTO permission(name)
//	VALUES($1)
//	RETURNING id, name, created_at, updated_at, deleted_at
func (q *Queries) PerRollCreateNewPermission(ctx context.Context, name string) (Permission, error) {
	row := q.db.QueryRow(ctx, perRollCreateNewPermission, name)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const perRollCreateNewRole = `-- name: PerRollCreateNewRole :one
INSERT INTO role(name)
VALUES($1)
RETURNING id, name, created_at, updated_at, deleted_at
`

// PerRollCreateNewRole
//
//	INSERT INTO role(name)
//	VALUES($1)
//	RETURNING id, name, created_at, updated_at, deleted_at
func (q *Queries) PerRollCreateNewRole(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRow(ctx, perRollCreateNewRole, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const perRollGetAllPermissions = `-- name: PerRollGetAllPermissions :many
SELECT id,
    name,
    created_at,
    updated_at
FROM permission
`

type PerRollGetAllPermissionsRow struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// PerRollGetAllPermissions
//
//	SELECT id,
//	    name,
//	    created_at,
//	    updated_at
//	FROM permission
func (q *Queries) PerRollGetAllPermissions(ctx context.Context) ([]PerRollGetAllPermissionsRow, error) {
	rows, err := q.db.Query(ctx, perRollGetAllPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PerRollGetAllPermissionsRow{}
	for rows.Next() {
		var i PerRollGetAllPermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const perRollGetAllRole = `-- name: PerRollGetAllRole :many
SELECT id,
    name,
    created_at,
    updated_at
FROM role
`

type PerRollGetAllRoleRow struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// PerRollGetAllRole
//
//	SELECT id,
//	    name,
//	    created_at,
//	    updated_at
//	FROM role
func (q *Queries) PerRollGetAllRole(ctx context.Context) ([]PerRollGetAllRoleRow, error) {
	rows, err := q.db.Query(ctx, perRollGetAllRole)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PerRollGetAllRoleRow{}
	for rows.Next() {
		var i PerRollGetAllRoleRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const perRollGetRoleWithItsPermissions = `-- name: PerRollGetRoleWithItsPermissions :many
SELECT r.id as role_id,
    r.name as role_name,
    p.id as permission_id,
    p.name as permission_name
FROM role AS r
    JOIN role_permission AS rp ON r.id = rp.role_id
    JOIN permission AS p ON p.id = rp.permission_id
WHERE r.id = $1
`

type PerRollGetRoleWithItsPermissionsRow struct {
	RoleID         int32  `json:"role_id"`
	RoleName       string `json:"role_name"`
	PermissionID   int32  `json:"permission_id"`
	PermissionName string `json:"permission_name"`
}

// PerRollGetRoleWithItsPermissions
//
//	SELECT r.id as role_id,
//	    r.name as role_name,
//	    p.id as permission_id,
//	    p.name as permission_name
//	FROM role AS r
//	    JOIN role_permission AS rp ON r.id = rp.role_id
//	    JOIN permission AS p ON p.id = rp.permission_id
//	WHERE r.id = $1
func (q *Queries) PerRollGetRoleWithItsPermissions(ctx context.Context, id int32) ([]PerRollGetRoleWithItsPermissionsRow, error) {
	rows, err := q.db.Query(ctx, perRollGetRoleWithItsPermissions, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PerRollGetRoleWithItsPermissionsRow{}
	for rows.Next() {
		var i PerRollGetRoleWithItsPermissionsRow
		if err := rows.Scan(
			&i.RoleID,
			&i.RoleName,
			&i.PermissionID,
			&i.PermissionName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const perRollRemovePermissionFromRole = `-- name: PerRollRemovePermissionFromRole :exec
DELETE FROM role_permission
WHERE role_id = $1
    AND permission_id = $2
`

type PerRollRemovePermissionFromRoleParams struct {
	RoleID       int32 `json:"role_id"`
	PermissionID int32 `json:"permission_id"`
}

// PerRollRemovePermissionFromRole
//
//	DELETE FROM role_permission
//	WHERE role_id = $1
//	    AND permission_id = $2
func (q *Queries) PerRollRemovePermissionFromRole(ctx context.Context, arg PerRollRemovePermissionFromRoleParams) error {
	_, err := q.db.Exec(ctx, perRollRemovePermissionFromRole, arg.RoleID, arg.PermissionID)
	return err
}

const perRollSoftDeletePermission = `-- name: PerRollSoftDeletePermission :exec
UPDATE permission
SET deleted_at = NOW()
WHERE id = $1
`

// PerRollSoftDeletePermission
//
//	UPDATE permission
//	SET deleted_at = NOW()
//	WHERE id = $1
func (q *Queries) PerRollSoftDeletePermission(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, perRollSoftDeletePermission, id)
	return err
}

const perRollSoftDeleteRole = `-- name: PerRollSoftDeleteRole :exec
UPDATE role
SET deleted_at = NOW()
WHERE id = $1
`

// PerRollSoftDeleteRole
//
//	UPDATE role
//	SET deleted_at = NOW()
//	WHERE id = $1
func (q *Queries) PerRollSoftDeleteRole(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, perRollSoftDeleteRole, id)
	return err
}
