// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"context"
)

type Querier interface {
	//GetUserById
	//
	//  SELECT id, username, profile_image, first_name, last_name, blocked_at, created_at, updated_at, deleted_at, role_id
	//  FROM users
	//  WHERE id = $1
	//  LIMIT 1
	GetUserById(ctx context.Context, id int32) (User, error)
	//GetUserBySessionToken
	//
	//  SELECT u.id, u.username, u.profile_image, u.first_name, u.last_name, u.blocked_at, u.created_at, u.updated_at, u.deleted_at, u.role_id
	//  FROM session AS s
	//      JOIN login_option AS lo ON s.originated_from = lo.id
	//      JOIN users AS u ON u.id = lo.user_id
	//  WHERE s.token = $1
	//      AND s.deleted_at IS NULL
	//      AND s.expires_at > NOW()
	//  LIMIT 1
	GetUserBySessionToken(ctx context.Context, token string) (User, error)
}

var _ Querier = (*Queries)(nil)
