// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: session.sql

package database

import (
	"context"
)

const softDeleteSession = `-- name: SoftDeleteSession :exec
UPDATE session
SET deleted_at = NOW()
WHERE id = $1
`

// SoftDeleteSession
//
//	UPDATE session
//	SET deleted_at = NOW()
//	WHERE id = $1
func (q *Queries) SoftDeleteSession(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, softDeleteSession, id)
	return err
}
