// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: todo.sql

package database

import (
	"context"
)

const todoSoftDeleteTodo = `-- name: TodoSoftDeleteTodo :exec
UPDATE todo
SET deleted_at = NOW()
WHERE id = $1
`

// TodoSoftDeleteTodo
//
//	UPDATE todo
//	SET deleted_at = NOW()
//	WHERE id = $1
func (q *Queries) TodoSoftDeleteTodo(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, todoSoftDeleteTodo, id)
	return err
}
