// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: todo.sql

package database

import (
	"context"
)

const softDeleteTodo = `-- name: SoftDeleteTodo :exec
UPDATE todo
SET deleted_at = NOW()
WHERE id = $1
`

// SoftDeleteTodo
//
//	UPDATE todo
//	SET deleted_at = NOW()
//	WHERE id = $1
func (q *Queries) SoftDeleteTodo(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, softDeleteTodo, id)
	return err
}
