// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: verification.sql

package database

import (
	"context"
)

const softDeleteVerification = `-- name: SoftDeleteVerification :exec
UPDATE verification
SET deleted_at = NOW()
WHERE id = $1
`

// SoftDeleteVerification
//
//	UPDATE verification
//	SET deleted_at = NOW()
//	WHERE id = $1
func (q *Queries) SoftDeleteVerification(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, softDeleteVerification, id)
	return err
}
