// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package database_queries

import (
	"context"
)

// iteratorForPermAddPermissionsToRoles implements pgx.CopyFromSource.
type iteratorForPermAddPermissionsToRoles struct {
	rows                 []PermAddPermissionsToRolesParams
	skippedFirstNextCall bool
}

func (r *iteratorForPermAddPermissionsToRoles) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForPermAddPermissionsToRoles) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].RoleName,
		r.rows[0].PermissionName,
	}, nil
}

func (r iteratorForPermAddPermissionsToRoles) Err() error {
	return nil
}

// PermAddPermissionsToRoles
//
//	INSERT INTO role_permission(role_name, permission_name)
//	VALUES($1, $2)
func (q *Queries) PermAddPermissionsToRoles(ctx context.Context, arg []PermAddPermissionsToRolesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"role_permission"}, []string{"role_name", "permission_name"}, &iteratorForPermAddPermissionsToRoles{rows: arg})
}

// iteratorForPermCreateNewPermissions implements pgx.CopyFromSource.
type iteratorForPermCreateNewPermissions struct {
	rows                 []string
	skippedFirstNextCall bool
}

func (r *iteratorForPermCreateNewPermissions) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForPermCreateNewPermissions) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0],
	}, nil
}

func (r iteratorForPermCreateNewPermissions) Err() error {
	return nil
}

// PermCreateNewPermissions
//
//	INSERT INTO permission(name)
//	VALUES($1)
func (q *Queries) PermCreateNewPermissions(ctx context.Context, name []string) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"permission"}, []string{"name"}, &iteratorForPermCreateNewPermissions{rows: name})
}

// iteratorForPermCreateNewRoles implements pgx.CopyFromSource.
type iteratorForPermCreateNewRoles struct {
	rows                 []string
	skippedFirstNextCall bool
}

func (r *iteratorForPermCreateNewRoles) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForPermCreateNewRoles) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0],
	}, nil
}

func (r iteratorForPermCreateNewRoles) Err() error {
	return nil
}

// PermCreateNewRoles
//
//	INSERT INTO role(name)
//	VALUES($1)
func (q *Queries) PermCreateNewRoles(ctx context.Context, name []string) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"role"}, []string{"name"}, &iteratorForPermCreateNewRoles{rows: name})
}
