// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: installation.sql

package database_queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const installationAttachSessionToInstallationById = `-- name: InstallationAttachSessionToInstallationById :execrows
UPDATE installation
SET attach_to = $2,
    last_attach_to= NULL
WHERE id = $1
    AND attach_to IS NULL
`

type InstallationAttachSessionToInstallationByIdParams struct {
	ID       int32       `json:"id"`
	AttachTo pgtype.Int4 `json:"attach_to"`
}

// InstallationAttachSessionToInstallationById
//
//	UPDATE installation
//	SET attach_to = $2,
//	    last_attach_to= NULL
//	WHERE id = $1
//	    AND attach_to IS NULL
func (q *Queries) InstallationAttachSessionToInstallationById(ctx context.Context, arg InstallationAttachSessionToInstallationByIdParams) (int64, error) {
	result, err := q.db.Exec(ctx, installationAttachSessionToInstallationById, arg.ID, arg.AttachTo)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const installationAttachSessionToInstallationByToken = `-- name: InstallationAttachSessionToInstallationByToken :exec
UPDATE installation
SET attach_to = $2,
    last_attach_to= NULL
WHERE installation_token = $1
    AND attach_to IS NULL
`

type InstallationAttachSessionToInstallationByTokenParams struct {
	InstallationToken string      `json:"installation_token"`
	AttachTo          pgtype.Int4 `json:"attach_to"`
}

// InstallationAttachSessionToInstallationByToken
//
//	UPDATE installation
//	SET attach_to = $2,
//	    last_attach_to= NULL
//	WHERE installation_token = $1
//	    AND attach_to IS NULL
func (q *Queries) InstallationAttachSessionToInstallationByToken(ctx context.Context, arg InstallationAttachSessionToInstallationByTokenParams) error {
	_, err := q.db.Exec(ctx, installationAttachSessionToInstallationByToken, arg.InstallationToken, arg.AttachTo)
	return err
}

const installationCreateNewInstallation = `-- name: InstallationCreateNewInstallation :exec
INSERT INTO installation (
        installation_token,
        notification_token,
        locale,
        timezone_offset_in_minutes,
        device_manufacturer,
        device_os,
        client_type,
        device_os_version,
        app_version
    )
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InstallationCreateNewInstallationParams struct {
	InstallationToken       string      `json:"installation_token"`
	NotificationToken       pgtype.Text `json:"notification_token"`
	Locale                  string      `json:"locale"`
	TimezoneOffsetInMinutes int32       `json:"timezone_offset_in_minutes"`
	DeviceManufacturer      pgtype.Text `json:"device_manufacturer"`
	DeviceOs                string      `json:"device_os"`
	ClientType              string      `json:"client_type"`
	DeviceOsVersion         pgtype.Text `json:"device_os_version"`
	AppVersion              string      `json:"app_version"`
}

// InstallationCreateNewInstallation
//
//	INSERT INTO installation (
//	        installation_token,
//	        notification_token,
//	        locale,
//	        timezone_offset_in_minutes,
//	        device_manufacturer,
//	        device_os,
//	        client_type,
//	        device_os_version,
//	        app_version
//	    )
//	VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
func (q *Queries) InstallationCreateNewInstallation(ctx context.Context, arg InstallationCreateNewInstallationParams) error {
	_, err := q.db.Exec(ctx, installationCreateNewInstallation,
		arg.InstallationToken,
		arg.NotificationToken,
		arg.Locale,
		arg.TimezoneOffsetInMinutes,
		arg.DeviceManufacturer,
		arg.DeviceOs,
		arg.ClientType,
		arg.DeviceOsVersion,
		arg.AppVersion,
	)
	return err
}

const installationDetachSessionFromInstallationById = `-- name: InstallationDetachSessionFromInstallationById :exec
UPDATE installation
SET attach_to = NULL,
    last_attach_to = $2
WHERE id = $1
`

type InstallationDetachSessionFromInstallationByIdParams struct {
	ID           int32       `json:"id"`
	LastAttachTo pgtype.Int4 `json:"last_attach_to"`
}

// InstallationDetachSessionFromInstallationById
//
//	UPDATE installation
//	SET attach_to = NULL,
//	    last_attach_to = $2
//	WHERE id = $1
func (q *Queries) InstallationDetachSessionFromInstallationById(ctx context.Context, arg InstallationDetachSessionFromInstallationByIdParams) error {
	_, err := q.db.Exec(ctx, installationDetachSessionFromInstallationById, arg.ID, arg.LastAttachTo)
	return err
}

const installationDetachSessionFromInstallationByToken = `-- name: InstallationDetachSessionFromInstallationByToken :exec
UPDATE installation
SET attach_to = NULL,
        last_attach_to = $2
WHERE installation_token = $1
`

type InstallationDetachSessionFromInstallationByTokenParams struct {
	InstallationToken string      `json:"installation_token"`
	LastAttachTo      pgtype.Int4 `json:"last_attach_to"`
}

// InstallationDetachSessionFromInstallationByToken
//
//	UPDATE installation
//	SET attach_to = NULL,
//	        last_attach_to = $2
//	WHERE installation_token = $1
func (q *Queries) InstallationDetachSessionFromInstallationByToken(ctx context.Context, arg InstallationDetachSessionFromInstallationByTokenParams) error {
	_, err := q.db.Exec(ctx, installationDetachSessionFromInstallationByToken, arg.InstallationToken, arg.LastAttachTo)
	return err
}

const installationDetachSessionFromInstallationByUserId = `-- name: InstallationDetachSessionFromInstallationByUserId :exec
UPDATE installation AS i
SET
    attach_to      = NULL,
    last_attach_to = s.id
FROM active_session AS s
JOIN active_login_identity AS li
    ON s.originated_from = li.id
WHERE
    li.user_id            = $1
    AND i.attach_to       = s.id
    AND i.last_attach_to IS NULL
    AND i.deleted_at     IS NULL
`

// InstallationDetachSessionFromInstallationByUserId
//
//	UPDATE installation AS i
//	SET
//	    attach_to      = NULL,
//	    last_attach_to = s.id
//	FROM active_session AS s
//	JOIN active_login_identity AS li
//	    ON s.originated_from = li.id
//	WHERE
//	    li.user_id            = $1
//	    AND i.attach_to       = s.id
//	    AND i.last_attach_to IS NULL
//	    AND i.deleted_at     IS NULL
func (q *Queries) InstallationDetachSessionFromInstallationByUserId(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, installationDetachSessionFromInstallationByUserId, userID)
	return err
}

const installationGetInstallationUsingToken = `-- name: InstallationGetInstallationUsingToken :one
SELECT id, installation_token, notification_token, locale, timezone_offset_in_minutes, device_manufacturer, device_os, client_type, device_os_version, app_version, created_at, updated_at, deleted_at, attach_to, last_attach_to
FROM installation
WHERE installation_token = $1
    AND deleted_at IS NULL
LIMIT 1
`

// InstallationGetInstallationUsingToken
//
//	SELECT id, installation_token, notification_token, locale, timezone_offset_in_minutes, device_manufacturer, device_os, client_type, device_os_version, app_version, created_at, updated_at, deleted_at, attach_to, last_attach_to
//	FROM installation
//	WHERE installation_token = $1
//	    AND deleted_at IS NULL
//	LIMIT 1
func (q *Queries) InstallationGetInstallationUsingToken(ctx context.Context, installationToken string) (Installation, error) {
	row := q.db.QueryRow(ctx, installationGetInstallationUsingToken, installationToken)
	var i Installation
	err := row.Scan(
		&i.ID,
		&i.InstallationToken,
		&i.NotificationToken,
		&i.Locale,
		&i.TimezoneOffsetInMinutes,
		&i.DeviceManufacturer,
		&i.DeviceOs,
		&i.ClientType,
		&i.DeviceOsVersion,
		&i.AppVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AttachTo,
		&i.LastAttachTo,
	)
	return i, err
}

const installationGetInstallationUsingTokenAndWhereAttachTo = `-- name: InstallationGetInstallationUsingTokenAndWhereAttachTo :one
SELECT id, installation_token, notification_token, locale, timezone_offset_in_minutes, device_manufacturer, device_os, client_type, device_os_version, app_version, created_at, updated_at, deleted_at, attach_to, last_attach_to
FROM installation
WHERE installation_token = $1
    AND attach_to = $2
    AND deleted_at IS NULL
LIMIT 1
`

type InstallationGetInstallationUsingTokenAndWhereAttachToParams struct {
	InstallationToken string      `json:"installation_token"`
	AttachTo          pgtype.Int4 `json:"attach_to"`
}

// InstallationGetInstallationUsingTokenAndWhereAttachTo
//
//	SELECT id, installation_token, notification_token, locale, timezone_offset_in_minutes, device_manufacturer, device_os, client_type, device_os_version, app_version, created_at, updated_at, deleted_at, attach_to, last_attach_to
//	FROM installation
//	WHERE installation_token = $1
//	    AND attach_to = $2
//	    AND deleted_at IS NULL
//	LIMIT 1
func (q *Queries) InstallationGetInstallationUsingTokenAndWhereAttachTo(ctx context.Context, arg InstallationGetInstallationUsingTokenAndWhereAttachToParams) (Installation, error) {
	row := q.db.QueryRow(ctx, installationGetInstallationUsingTokenAndWhereAttachTo, arg.InstallationToken, arg.AttachTo)
	var i Installation
	err := row.Scan(
		&i.ID,
		&i.InstallationToken,
		&i.NotificationToken,
		&i.Locale,
		&i.TimezoneOffsetInMinutes,
		&i.DeviceManufacturer,
		&i.DeviceOs,
		&i.ClientType,
		&i.DeviceOsVersion,
		&i.AppVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AttachTo,
		&i.LastAttachTo,
	)
	return i, err
}

const installationSoftDeleteInstallation = `-- name: InstallationSoftDeleteInstallation :exec
UPDATE installation
SET deleted_at = NOW()
WHERE id = $1
`

// InstallationSoftDeleteInstallation
//
//	UPDATE installation
//	SET deleted_at = NOW()
//	WHERE id = $1
func (q *Queries) InstallationSoftDeleteInstallation(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, installationSoftDeleteInstallation, id)
	return err
}

const installationUpdateInstallation = `-- name: InstallationUpdateInstallation :exec
UPDATE installation
SET notification_token = $2,
    locale = $3,
    timezone_Offset_in_minutes = $4,
    app_version = $5
WHERE installation_token = $1
    AND deleted_at IS NULL
`

type InstallationUpdateInstallationParams struct {
	InstallationToken       string      `json:"installation_token"`
	NotificationToken       pgtype.Text `json:"notification_token"`
	Locale                  string      `json:"locale"`
	TimezoneOffsetInMinutes int32       `json:"timezone_offset_in_minutes"`
	AppVersion              string      `json:"app_version"`
}

// InstallationUpdateInstallation
//
//	UPDATE installation
//	SET notification_token = $2,
//	    locale = $3,
//	    timezone_Offset_in_minutes = $4,
//	    app_version = $5
//	WHERE installation_token = $1
//	    AND deleted_at IS NULL
func (q *Queries) InstallationUpdateInstallation(ctx context.Context, arg InstallationUpdateInstallationParams) error {
	_, err := q.db.Exec(ctx, installationUpdateInstallation,
		arg.InstallationToken,
		arg.NotificationToken,
		arg.Locale,
		arg.TimezoneOffsetInMinutes,
		arg.AppVersion,
	)
	return err
}
