// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oidc_data.sql

package database_queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const oidcDataUpdateRecored = `-- name: OidcDataUpdateRecored :exec
UPDATE oidc_data
SET email = $1::text,
    given_name = $2::text,
    family_name = $3::text,
    name = $4::text,
    picture = $5::text
WHERE id = $6
`

type OidcDataUpdateRecoredParams struct {
	Email      pgtype.Text `json:"email"`
	GivenName  pgtype.Text `json:"given_name"`
	FamilyName pgtype.Text `json:"family_name"`
	Name       pgtype.Text `json:"name"`
	Picture    pgtype.Text `json:"picture"`
	ID         int32       `json:"id"`
}

// OidcDataUpdateRecored
//
//	UPDATE oidc_data
//	SET email = $1::text,
//	    given_name = $2::text,
//	    family_name = $3::text,
//	    name = $4::text,
//	    picture = $5::text
//	WHERE id = $6
func (q *Queries) OidcDataUpdateRecored(ctx context.Context, arg OidcDataUpdateRecoredParams) error {
	_, err := q.db.Exec(ctx, oidcDataUpdateRecored,
		arg.Email,
		arg.GivenName,
		arg.FamilyName,
		arg.Name,
		arg.Picture,
		arg.ID,
	)
	return err
}
