// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permission_and_role.sql

package database_queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const permAddPermissionToRole = `-- name: PermAddPermissionToRole :exec
INSERT INTO role_permission(role_name, permission_name)
VALUES($1, $2)
`

type PermAddPermissionToRoleParams struct {
	RoleName       string `json:"role_name"`
	PermissionName string `json:"permission_name"`
}

// PermAddPermissionToRole
//
//	INSERT INTO role_permission(role_name, permission_name)
//	VALUES($1, $2)
func (q *Queries) PermAddPermissionToRole(ctx context.Context, arg PermAddPermissionToRoleParams) error {
	_, err := q.db.Exec(ctx, permAddPermissionToRole, arg.RoleName, arg.PermissionName)
	return err
}

const permCreateNewPermission = `-- name: PermCreateNewPermission :one
INSERT INTO permission(name)
VALUES($1)
RETURNING name, created_at, updated_at, deleted_at
`

// PermCreateNewPermission
//
//	INSERT INTO permission(name)
//	VALUES($1)
//	RETURNING name, created_at, updated_at, deleted_at
func (q *Queries) PermCreateNewPermission(ctx context.Context, name string) (Permission, error) {
	row := q.db.QueryRow(ctx, permCreateNewPermission, name)
	var i Permission
	err := row.Scan(
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const permCreateNewRole = `-- name: PermCreateNewRole :one
INSERT INTO role(name)
VALUES($1)
RETURNING name, created_at, updated_at, deleted_at
`

// PermCreateNewRole
//
//	INSERT INTO role(name)
//	VALUES($1)
//	RETURNING name, created_at, updated_at, deleted_at
func (q *Queries) PermCreateNewRole(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRow(ctx, permCreateNewRole, name)
	var i Role
	err := row.Scan(
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const permGetAllPermissions = `-- name: PermGetAllPermissions :many
SELECT
    name,
    created_at,
    updated_at
FROM permission
`

type PermGetAllPermissionsRow struct {
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// PermGetAllPermissions
//
//	SELECT
//	    name,
//	    created_at,
//	    updated_at
//	FROM permission
func (q *Queries) PermGetAllPermissions(ctx context.Context) ([]PermGetAllPermissionsRow, error) {
	rows, err := q.db.Query(ctx, permGetAllPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PermGetAllPermissionsRow{}
	for rows.Next() {
		var i PermGetAllPermissionsRow
		if err := rows.Scan(&i.Name, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const permGetAllRoles = `-- name: PermGetAllRoles :many
SELECT
    name,
    created_at,
    updated_at
FROM role
`

type PermGetAllRolesRow struct {
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// PermGetAllRoles
//
//	SELECT
//	    name,
//	    created_at,
//	    updated_at
//	FROM role
func (q *Queries) PermGetAllRoles(ctx context.Context) ([]PermGetAllRolesRow, error) {
	rows, err := q.db.Query(ctx, permGetAllRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PermGetAllRolesRow{}
	for rows.Next() {
		var i PermGetAllRolesRow
		if err := rows.Scan(&i.Name, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const permGetRoleWithItsPermissions = `-- name: PermGetRoleWithItsPermissions :many
SELECT
    r.name as role_name,
    p.name as permission_name
FROM role AS r
    JOIN role_permission AS rp ON r.name = rp.role_name
    JOIN permission AS p ON p.name = rp.permission_name
WHERE r.name = $1
`

type PermGetRoleWithItsPermissionsRow struct {
	RoleName       string `json:"role_name"`
	PermissionName string `json:"permission_name"`
}

// PermGetRoleWithItsPermissions
//
//	SELECT
//	    r.name as role_name,
//	    p.name as permission_name
//	FROM role AS r
//	    JOIN role_permission AS rp ON r.name = rp.role_name
//	    JOIN permission AS p ON p.name = rp.permission_name
//	WHERE r.name = $1
func (q *Queries) PermGetRoleWithItsPermissions(ctx context.Context, name string) ([]PermGetRoleWithItsPermissionsRow, error) {
	rows, err := q.db.Query(ctx, permGetRoleWithItsPermissions, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PermGetRoleWithItsPermissionsRow{}
	for rows.Next() {
		var i PermGetRoleWithItsPermissionsRow
		if err := rows.Scan(&i.RoleName, &i.PermissionName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const permRemovePermissionFromRole = `-- name: PermRemovePermissionFromRole :exec
DELETE FROM role_permission
WHERE role_name = $1
    AND permission_name = $2
`

type PermRemovePermissionFromRoleParams struct {
	RoleName       string `json:"role_name"`
	PermissionName string `json:"permission_name"`
}

// PermRemovePermissionFromRole
//
//	DELETE FROM role_permission
//	WHERE role_name = $1
//	    AND permission_name = $2
func (q *Queries) PermRemovePermissionFromRole(ctx context.Context, arg PermRemovePermissionFromRoleParams) error {
	_, err := q.db.Exec(ctx, permRemovePermissionFromRole, arg.RoleName, arg.PermissionName)
	return err
}

const permSoftDeletePermission = `-- name: PermSoftDeletePermission :exec
UPDATE permission
SET deleted_at = NOW()
WHERE name = $1
`

// PermSoftDeletePermission
//
//	UPDATE permission
//	SET deleted_at = NOW()
//	WHERE name = $1
func (q *Queries) PermSoftDeletePermission(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, permSoftDeletePermission, name)
	return err
}

const permSoftDeleteRole = `-- name: PermSoftDeleteRole :exec
UPDATE role
SET deleted_at = NOW()
WHERE name = $1
`

// PermSoftDeleteRole
//
//	UPDATE role
//	SET deleted_at = NOW()
//	WHERE name = $1
func (q *Queries) PermSoftDeleteRole(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, permSoftDeleteRole, name)
	return err
}
