// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seeder.sql

package database_queries

import (
	"context"
)

const seederVersionAddValue = `-- name: SeederVersionAddValue :exec
INSERT INTO seeder_version (
  version
)
VALUES (
  $1
)
`

// SeederVersionAddValue
//
//	INSERT INTO seeder_version (
//	  version
//	)
//	VALUES (
//	  $1
//	)
func (q *Queries) SeederVersionAddValue(ctx context.Context, version int32) error {
	_, err := q.db.Exec(ctx, seederVersionAddValue, version)
	return err
}

const seederVersionReadLatestAppliedVersion = `-- name: SeederVersionReadLatestAppliedVersion :one
SELECT
  version
FROM
  seeder_version
ORDER BY
  version DESC
LIMIT 1
`

// SeederVersionReadLatestAppliedVersion
//
//	SELECT
//	  version
//	FROM
//	  seeder_version
//	ORDER BY
//	  version DESC
//	LIMIT 1
func (q *Queries) SeederVersionReadLatestAppliedVersion(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, seederVersionReadLatestAppliedVersion)
	var version int32
	err := row.Scan(&version)
	return version, err
}
