// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package database_queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const settingsCreateLabel = `-- name: SettingsCreateLabel :exec
INSERT INTO settings (
    label
)
VALUES (
    $1::TEXT
)
ON CONFLICT (label)
DO NOTHING
`

// SettingsCreateLabel
//
//	INSERT INTO settings (
//	    label
//	)
//	VALUES (
//	    $1::TEXT
//	)
//	ON CONFLICT (label)
//	DO NOTHING
func (q *Queries) SettingsCreateLabel(ctx context.Context, label string) error {
	_, err := q.db.Exec(ctx, settingsCreateLabel, label)
	return err
}

const settingsDeleteByLable = `-- name: SettingsDeleteByLable :exec
DELETE FROM settings
WHERE label = $1::TEXT
`

// SettingsDeleteByLable
//
//	DELETE FROM settings
//	WHERE label = $1::TEXT
func (q *Queries) SettingsDeleteByLable(ctx context.Context, label string) error {
	_, err := q.db.Exec(ctx, settingsDeleteByLable, label)
	return err
}

const settingsGetByLable = `-- name: SettingsGetByLable :one
SELECT label, value, created_at, updated_at FROM settings
WHERE label = $1::TEXT
LIMIT 1
`

// SettingsGetByLable
//
//	SELECT label, value, created_at, updated_at FROM settings
//	WHERE label = $1::TEXT
//	LIMIT 1
func (q *Queries) SettingsGetByLable(ctx context.Context, label string) (Setting, error) {
	row := q.db.QueryRow(ctx, settingsGetByLable, label)
	var i Setting
	err := row.Scan(
		&i.Label,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const settingsSetSetting = `-- name: SettingsSetSetting :exec
INSERT INTO settings (
    label,
    value
)
VALUES (
    $1::TEXT,
    $2::TEXT
)
ON CONFLICT (label)
DO UPDATE
SET value = EXCLUDED.value
`

type SettingsSetSettingParams struct {
	Label string      `json:"label"`
	Value pgtype.Text `json:"value"`
}

// SettingsSetSetting
//
//	INSERT INTO settings (
//	    label,
//	    value
//	)
//	VALUES (
//	    $1::TEXT,
//	    $2::TEXT
//	)
//	ON CONFLICT (label)
//	DO UPDATE
//	SET value = EXCLUDED.value
func (q *Queries) SettingsSetSetting(ctx context.Context, arg SettingsSetSettingParams) error {
	_, err := q.db.Exec(ctx, settingsSetSetting, arg.Label, arg.Value)
	return err
}
